export const ADMIN_ROUTE='/admin'
export const ORDER_ROUTE='/order'
export const LOGIN_ROUTE='/login'
export const REGISTRATION_ROUTE='/registration'
export const MAIN_ROUTE='/main'
export const SERVICES_ROUTE='/services'
export const STAFF_ROUTE='/staff'